apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnixapp--deployment
  labels:
    app: ngnixapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngnixapp
  template:
    metadata:
      labels:
        app:ngnixapp
    spec:
      containers:
        - name: ngnixapp
          image: aksdevopsacr.azurecr.io/custom2aksnginxapp1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-nginx-loadbalancer-service
  labels:
    app: ngnixapp
spec:
  type: LoadBalancer
  selector:
    app: ngnixapp
  ports:
    - port: 80
      targetPort: 80



